version: "3.2"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8080:80"
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - mysql_volume:/var/lib/mysql
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: phpmyadmin
volumes:
  mysql_volume: